TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += motorHome.template
DB += motorHomeCommon.template
DB += motorHomeLimit.template
DB += motorHomeMotorRecord.template
DB += motorHomeOffSet.template
DB += motorHomePosSet.template

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

